import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, posix, relative, sep } from 'node:path';

/**
 * The service worker is written at build time, because it has to name files
 * only the build knows: Vite hashes every asset, and a worker that precached
 * `main.js` would precache nothing.
 *
 * Everything here is deliberately dependency-free and small enough to read in
 * one sitting. Workbox would generate a better worker; it would also generate a
 * worker nobody on this project could debug, for a game whose entire offline
 * story is "a canvas, a bundle and a `localStorage` key".
 */

/** Files that must never be precached, whatever the build emits. */
const EXCLUDED = new Set(['sw.js', 'og-image.png']);

/** Extensions worth shipping into the cache. Source maps are not. */
const EXCLUDED_EXTENSIONS = ['.map', '.zip', '.md'];

/** Every file under `dir`, as paths relative to it, in a stable order. */
export function walk(dir, base = dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full, base));
    else out.push(relative(base, full).split(sep).join(posix.sep));
  }
  return out.sort();
}

/** The subset of `files` the worker should precache. */
export function precacheList(files) {
  return files.filter(
    (file) =>
      !EXCLUDED.has(file) && !EXCLUDED_EXTENSIONS.some((extension) => file.endsWith(extension)),
  );
}

/**
 * A short hash of the precached files' contents, used as the cache name.
 *
 * Content rather than a timestamp: two builds of unchanged source produce the
 * same cache, so a redeploy that changed nothing does not evict a player's
 * offline copy and re-download it.
 */
export function buildId(dir, files) {
  const hash = createHash('sha256');
  for (const file of files) {
    hash.update(file);
    hash.update(readFileSync(join(dir, file)));
  }
  return hash.digest('hex').slice(0, 12);
}

/**
 * The worker's source.
 *
 * Two strategies, because the two kinds of request want opposite things:
 *
 * - **Navigations go to the network first**, falling back to the cached shell.
 *   The shell is the one URL that is not content-hashed, so cache-first would
 *   pin a player to the build they first opened until their cache was cleared.
 * - **Everything else is cache-first.** Hashed asset names cannot go stale by
 *   definition, and cache-first is what makes the game start instantly on a
 *   phone with two bars.
 *
 * There is no `skipWaiting`: swapping the assets under a running tab is how a
 * game ends up with half of one build and half of another. A new worker takes
 * over the next time the game is opened fresh.
 */
export function serviceWorkerSource({ cacheName, assets, shell = 'index.html' }) {
  return `/*
 * Old Growth — service worker. GENERATED by scripts/build-sw.mjs; do not edit.
 *
 * Precaches the app shell so the game opens with no network at all, which for
 * an idle game is not a nicety: the tree keeps growing while the tab is closed,
 * and a player checking in from a train should see it.
 */
const CACHE = ${JSON.stringify(cacheName)};
const SHELL = ${JSON.stringify(shell)};
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      // Individually, so one 404 cannot fail the whole install and leave the
      // player with no offline copy at all.
      Promise.all(
        ASSETS.map((asset) =>
          cache.add(new Request(asset, { cache: 'reload' })).catch(() => undefined),
        ),
      ),
    ),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE && key.startsWith('old-growth-')).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(SHELL, copy));
          return response;
        })
        .catch(() => caches.match(SHELL).then((cached) => cached || Response.error())),
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    }),
  );
});
`;
}
